name: Prepare the builds for a deploy.
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out our code
      uses: actions/checkout@main
    - name: say something
      run: |
       echo "A little less conversation"
       echo "A little more testing PREPARE."