name: Release CI

on:
  workflow_dispatch:

env:
  REGISTRY_NAME: gcr.io
  VERSION: 1.2

jobs:
  release:
    name: Run Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@main
      - name: ENV Variable Test (Release)
        run: bash ./release.sh
