name: Release [to GCR] CI

on:
  workflow_dispatch:

env:
  REGISTRY_NAME: gcr.io
  VERSION: 1.2

jobs:
  release:
    name: Run Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@main
      - name: Setup and configure the Google Cloud SDK.
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.CONTAINERS_PROJECT_ID }}
          service_account_key: ${{ secrets.GCR_TOKEN }}
          export_default_credentials: true
      - name: Run the GCP Docker authenticator.
        run: |
          gcloud auth configure-docker -q
