name: Release [GCR]

on:
  workflow_dispatch:

env:
  REGISTRY_NAME: gcr.io
  VERSION: 1.2

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@main
      - name: Configure the Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCR_TOKEN }}
          export_default_credentials: true
      - name: Run the GCP Docker authenticator.
        run: |
          gcloud auth configure-docker -q
      - name: Build and Deploy Containers
        run: bash ./release.sh
